services:
  - type: web
    name: video-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn BU-downloader.app:app
    envVars:
      - key: SECRET_KEY
        value: your-very-secret-key 
